name: Run Tests

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: crawl_test
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
        matrix:
            php-versions: ['7.4', '8.0']
            composer-flags: ["--prefer-lowest", ""]
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
           php-version: ${{ matrix.php-versions }}
    - name: Install Dependencies
      run: composer update ${composer-flags} --no-interaction --prefer-source
    - name: Seut up Database
      run: |
        mysql -u root -e "CREATE USER 'homestead'@'localhost' IDENTIFIED BY 'secret';"
        mysql -u root -e "GRANT ALL ON crawl_test.* TO 'homestead'@'localhost';"
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
